FEAT : ADDRESSES
HuynhKhaNhutTranB1910162/assignment pull request #6
Opened 2023-08-25 08:57 UTC by HuynhKhaNhutTranB1910162

2023-08-30 08:57 UTC, HuynhKhaNhutTranB1910162 commented
<img width="459" alt="image" src="https://github.com/HuynhKhaNhutTranB1910162/assignment/assets/114003080/5acb583a-2791-4e5b-a24c-bf97fcc2b5b4">

2023-08-31 07:40 UTC, voduchuy2001 requested changes

2023-08-31 07:40 UTC, voduchuy2001 commented on app/Http/Controllers/Client/OrderController.php
> +        }
Không cần viết như thế này nữa, apply middleware for route

2023-08-31 07:40 UTC, voduchuy2001 commented on app/Http/Controllers/Client/ProfileController.php
> +        }
Tương tự

2023-08-31 07:40 UTC, voduchuy2001 commented on app/Livewire/Location.php
> +            toastr()->warning('Dịa chỉ khong dc qua 3');
Chính tả

2023-08-31 07:40 UTC, voduchuy2001 commented on app/Livewire/Location.php
> +        if (!empty($this->provinceId)) {
(! $provinceId)
Ở dưới tương tự

2023-08-31 07:45 UTC, merged